### ISSUE TITLE
支持新协议，这里PRPC 实际是BRPC意思？是笔误吗？

### ISSUE THREAD

**Issue by janksenhu** [apache/brpc-website#158]
第一类协议：标记或特殊字符在最前面，比如[baidu_std](https://github.com/apache/brpc/blob/master/docs/cn/baidu_std.md)，hulu_pbrpc的前4个字符分别是**PRPC**和HULU，

这里PRPC 实际是BRPC意思？是笔误吗？

**Comment by wwbmmm** [comment]
不是笔误，就是PRPC。P是protobuf的意思
